################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "0.0.0.0"
    # Port on which we bind (default: 3000)
    port: 3000

################################################################################
##                               Logging options                              ##
################################################################################
logging:
    # Values: error, warn, info, http, verbose, debug, silly
    level: http

node:
  interval: 600
  max_txs: 256
  send_interval: 30
  ipfs_api_url: https://api-ipfs.bosagora.info
  ipfs_gateway_url: https://ipfs.bosagora.info
  ipfs_test: false

scheduler:
  enable: true
  items:
    - name: node
      enable: true
      interval: 1
    - name: send_block
      enable: true
      interval: 14

database:
  path: "${DB_PATH}"

contracts:
  managerKey: "${MANAGER_KEY}"
  purchaseAddress: "${STORE_PURCHASE_CONTRACT_ADDRESS}"

authorization:
  accessKey: "${ACCESS_KEY}"
