################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "0.0.0.0"
    # Port on which we bind (default: 3000)
    port: 3001

################################################################################
##                               Logging options                              ##
################################################################################
logging:
    # Values: error, warn, info, http, verbose, debug, silly
    level: debug

node:
  interval: 5
  max_txs: 8
  send_interval: 1
  ipfs_api_url: http://localhost:5001
  ipfs_gateway_url: http://localhost:8080
  ipfs_test: true

scheduler:
  enable: true
  items:
    - name: node
      enable: true
      expression: "*/1 * * * * *"
    - name: send_block
      enable: true
      expression: "*/1 * * * * *"

database:
  path: ":memory:"

contracts:
  managerKey: "${MANAGER_KEY}"
  purchaseAddress: "0x0000000000000000000000000000000000000000"

authorization:
  accessKey: "${ACCESS_KEY}"
