name: CI

on: [push, pull_request ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Check formatting of SDK
        run: cd packages/sdk && yarn run formatting:check
      - name: Compile of SDK
        run: cd packages/sdk && yarn run build
      - name: Tests of SDK
        run: cd packages/sdk && yarn run test

      - name: Check formatting of Contract
        run: cd packages/contracts && yarn run formatting:check
      - name: Compile of Contract
        run: cd packages/contracts && yarn run build
      - name: Run Hardhat Tests of Contract
        env:
          REPORT_GAS: true
        run: cd packages/contracts && yarn run test

      - name: Copy env of Server
        run: cp packages/server/env/.env.sample packages/server/env/.env
      - name: Check formatting of Server
        run: cd packages/server && yarn run formatting:check
      - name: Compile of Server
        run: cd packages/server && yarn run build
      - name: Tests of Server
        env:
          REPORT_GAS: true
        run: cd packages/server && yarn run test
